# Gradle
org.gradle.jvmargs  = -Xmx3G
org.gradle.daemon   = true
org.gradle.parallel = true
org.gradle.caching  = true

# Minecraft
minecraft_version       = 1.20.1
minecraft_version_range = [1.20, 1.20.2)

# Forge
forge_version       = 47.4.10
forge_version_range = [47,)

# Mapping
mapping_channel = parchment
mapping_version = 2023.09.03-1.20.1

# Mod Setting
mod_id          = profile_switcher
mod_name        = Profile Switcher
mod_version     = 0.0.1
mod_authors     = Higurashi
mod_credits     =
mod_license     = All Rights Reserved (See LICENSE.txt)
mod_description = Manage multiple player profiles and use different profiles across worlds.
mod_url         =
mod_issue       = https://github.com/Higurashi34m/Profile-Switcher/issues
mod_group_id    = dev.higurashi
